/*
 *
 *  default translation file - english translation
 *
 */

#pragma once

extern char TEXT_LANG[6];

extern char TEXT_INDEX_PAGE[16];
extern char TEXT_CONFIG_PAGE[14];

extern char TEXT_CONFIG_DEVICE_PAGE[24];
extern char TEXT_CONFIG_INFO_DEVICE_PAGE[144];
extern char TEXT_CONFIG_SERVICES_PAGE[24];
extern char TEXT_CONFIG_INFO_SERVICES_PAGE[144];

extern char TEXT_UPDATE_PAGE[14];

extern char TEXT_WEATHER[10];
extern char TEXT_TEMPERATURE[14];
extern char TEXT_HUMIDITY[14];
extern char TEXT_PRESSURE[14];
extern char TEXT_DEWPOINT[14];

extern char TEXT_AIRPOLLUTION[26];
extern char TEXT_SAVED[10];

extern char TEXT_POSTCONFIG_INFO[60];
extern char TEXT_INSTRUCIONSLINK[76];
extern char TEXT_DEVICENAME[20];
extern char TEXT_DEVICENAMEAUTO[32];
extern char TEXT_SELECTEDLANGUAGE[10];
extern char TEXT_TEMPHUMIPRESSSENSOR[40];
extern char TEXT_PMSENSOR[20];

extern char TEXT_FIRST_THP_SDA_SCL[40];
extern char TEXT_FIRST_THP_SDA[8];
extern char TEXT_FIRST_THP_SCL[8];

extern char TEXT_SECOND_THP[40];

extern char TEXT_SECOND_THP_SDA_SCL[48];
extern char TEXT_SECOND_THP_SDA[8];
extern char TEXT_SECOND_THP_SCL[8];

extern char TEXT_DUST_TX_RX[32];
extern char TEXT_DUST_TX[8];
extern char TEXT_DUST_RX[8];

extern char TEXT_FREQUENTMEASUREMENTONOFF[26];
extern char TEXT_FREQUENTMEASUREMENTINFO[80];
extern char TEXT_MEASUREMENTFREQUENCY[30];
extern char TEXT_AVERAGELASTRESULT[30];
extern char TEXT_PMMEASUREMENTS[18];
extern char TEXT_SENDINGINTERVAL[50];
extern char TEXT_SERVICESSENDINGINTERVAL[64];
extern char TEXT_DBSENDINGINTERVAL[50];
extern char TEXT_SECONDS[10];
extern char TEXT_MINUTES[10];

extern char TEXT_DEEPSLEEPINFO[540];
extern char TEXT_DEEPSLEEPINFO_ESP32[476];

extern char TEXT_DISPLAYPM1[30];
extern char TEXT_ALTITUDEINFO[116];

extern char TEXT_SECURECONFIGUPDATEPAGE[84];
extern char TEXT_SECURELOGIN[8];
extern char TEXT_SECUREPASSWD[10];
extern char TEXT_SECURELOGOUTINFO[48];

extern char TEXT_LUFTDATENSENDING[96];
extern char TEXT_LUFTDATEN_GRAPH_ON[64];

extern char TEXT_SMOGLISTSENDING[48];
extern char TEXT_SMOGLISTINFO[242];

extern char TEXT_AIRMONITORSENDING[128];
extern char TEXT_AIRMONITORCHARTS[48];
extern char TEXT_AIRMONITOR_API_KEY[32];

extern char TEXT_MY_COORDINATESINFO[74];
extern char TEXT_MY_LATITUDE[24];
extern char TEXT_MY_LONGITUDE[24];

extern char TEXT_THINGSPEAKSENDING[50];
extern char TEXT_THINGSPEAKCHARTS[48];
extern char TEXT_THINGSPEAK_WRITE_API_KEY[28];
extern char TEXT_THINGSPEAKCHANNELID[24];
extern char TEXT_THINGSPEAK_READ_API_KEY[28];

extern char TEXT_INFLUXDBSENDING[32];
extern char TEXT_INFLUXDBVERSION[18];
extern char TEXT_INFLUXDBSERVER[30];
extern char TEXT_INFLUXDBPORT[16];
extern char TEXT_INFLUXDBNAME[24];
extern char TEXT_INFLUXDBUSER[28];
extern char TEXT_INFLUXDBPASSWD[24];
extern char TEXT_INFLUXDBORG[16];
extern char TEXT_INFLUXDBBUCKET[10];
extern char TEXT_INFLUXDBTOKEN[8];

extern char TEXT_CONFIG_ADV_MQTT[22];
extern char TEXT_MQTTSENDING[34];
extern char TEXT_MQTTSERVER[22];
extern char TEXT_MQTTPORT[12];
extern char TEXT_MQTTUSER[20];
extern char TEXT_MQTTPASSWD[16];

extern char TEXT_MQTT_IP_IN_TOPIC[22];
extern char TEXT_MQTT_DEVICENAME_IN_TOPIC[30];
extern char TEXT_MQTT_TOPIC_INFO[256];
extern char TEXT_MQTT_SLASH_AT_THE_BEGINNING[40];
extern char TEXT_MQTT_SLASH_AT_THE_END[36];

extern char TEXT_AQIECOSENDING[100];
extern char TEXT_AQIECOSERVER[26];
extern char TEXT_AQIECOPATH[20];

extern char TEXT_CALIBMETHOD[22];
extern char TEXT_CALIB1[30];
extern char TEXT_CALIB2[30];
extern char TEXT_SOFTWATEVERSION[24];

extern char TEXT_ERASEWIFICONFIG[22];
extern char TEXT_RESTORESETTINGS[32];
extern char TEXT_SAVE[8];
extern char TEXT_YES[6];
extern char TEXT_NO[6];
extern char TEXT_WITHOUTSENSOR[16];
extern char TEXT_WITHOUTCALIBRATION[22];
extern char TEXT_AUTOMATICCALIBRATION[26];

extern char TEXT_INTL_EN[12];
extern char TEXT_INTL_PL[8];

extern char TEXT_FWUPDATEAVALIBLE[42];
extern char TEXT_AUTOUPDATEON[28];
extern char TEXT_MANUALUPDATEBUTTON[22];
extern char TEXT_FWUPDATEBUTTON[32];
extern char TEXT_AUTOUPDATEONBUTTON[36];
extern char TEXT_AUTOUPDATEWARNING[650];
extern char TEXT_UPDATEPAGEAUTOUPDATEWARNING[192];

extern char TEXT_SELECTUPDATEFILE[20];
extern char TEXT_SUBMITUPDATE[10];
extern char TEXT_CURRENTSOFTVERSION[40];
extern char TEXT_SERVERSOFTWAREVERSION[46];
extern char TEXT_LATESTAVAILABLESOFT[82];

extern char TEXT_HERE[8];
extern char TEXT_THEFORM[12];

extern char TEXT_CONNECTEDWIFI[28];
extern char TEXT_WIFIRSSI[28];
extern char TEXT_WIFIQUALITY[26];

extern char TEXT_HOMEKIT_SUPPORT[26];
extern char TEXT_HOMEKIT_IS_PAIRED[94];
extern char TEXT_PAGE_HOMEKIT_RESET[30];

extern char TEXT_AIRQUALITY_TOPIC[12];
